[Added] get dealts data
Make-a-good-soup/fugle-realtime-kotlin pull request #4
Opened 2023-01-03 10:50 UTC by dan12411

新增 get dealts method & data model.

2023-01-30 23:41 UTC, nick45chen approved these changes

2023-01-30 23:56 UTC, nick45chen requested changes

2023-01-30 23:56 UTC, nick45chen commented on fugle_realtime_lib/src/main/java/net/makeagoodsoup/fugle_realtime_lib/core/remote/services/IntradayService.kt
> +        @Query("apiToken") apiToken: String
@dan12411 缺少 parameters

<img width="912" alt="image" src="https://user-images.githubusercontent.com/17996728/215623112-2b87e12a-df04-49cd-816e-ef2d374f680f.png">

2023-01-30 23:56 UTC, nick45chen commented on fugle_realtime_lib/src/main/java/net/makeagoodsoup/fugle_realtime_lib/core/remote/services/IntradayService.kt
> +        @Query("apiToken") apiToken: String
btw  `limit` / `offset` / `oddLot` 為 optional parameter (有預設值)

2023-01-30 23:56 UTC, nick45chen commented on fugle_realtime_lib/src/main/java/net/makeagoodsoup/fugle_realtime_lib/core/repository/FugleHttpRepository.kt
> +    suspend fun getDealts(symbolId: String, apiToken: String): Result<DealtsData> {
同 https://github.com/Make-a-good-soup/fugle-realtime-kotlin/pull/4#discussion_r1091285375

2023-01-31 00:00 UTC, nick45chen commented on fugle_realtime_lib/src/main/java/net/makeagoodsoup/fugle_realtime_lib/core/remote/services/IntradayService.kt
> +        @Query("apiToken") apiToken: String
nickpick:  補上文件註解說明 https://kotlinlang.org/docs/coding-conventions.html#file-annotations

2023-01-31 00:00 UTC, nick45chen commented on fugle_realtime_lib/src/main/java/net/makeagoodsoup/fugle_realtime_lib/core/repository/FugleHttpRepository.kt
> +    suspend fun getDealts(symbolId: String, apiToken: String): Result<DealtsData> {
nickpick:  補上文件註解說明 https://kotlinlang.org/docs/coding-conventions.html#file-annotations

2023-01-31 12:27 UTC, nick45chen approved these changes

2023-01-31 12:27 UTC, dan12411 commented on fugle_realtime_lib/src/main/java/net/makeagoodsoup/fugle_realtime_lib/core/remote/services/IntradayService.kt
> +        @Query("apiToken") apiToken: String
感謝 @nick45chen 已修正 [ec9417f](https://github.com/Make-a-good-soup/fugle-realtime-kotlin/pull/4/commits/ec9417f90da9082d9a0e805dfafdb4867a7bbc65)

2023-01-31 12:27 UTC, dan12411 commented on fugle_realtime_lib/src/main/java/net/makeagoodsoup/fugle_realtime_lib/core/repository/FugleHttpRepository.kt
> +    suspend fun getDealts(symbolId: String, apiToken: String): Result<DealtsData> {
同上

2023-01-31 12:27 UTC, merged