[Added] get volumes data
Make-a-good-soup/fugle-realtime-kotlin pull request #6
Opened 2023-01-15 07:23 UTC by dan12411

新增 get volumes method & data model.

2023-01-30 23:50 UTC, nick45chen requested changes

2023-01-30 23:50 UTC, nick45chen commented on fugle_realtime_lib/src/main/java/net/makeagoodsoup/fugle_realtime_lib/core/entities/Volume.kt
> +    val price: Double, // 成交價
@dan12411 不太確定是不是文件寫錯，price 是 String type

<img width="378" alt="image" src="https://user-images.githubusercontent.com/17996728/215622658-eb00d265-4463-4db3-b8c6-2e8fbf995678.png">

2023-01-30 23:50 UTC, nick45chen commented on fugle_realtime_lib/src/main/java/net/makeagoodsoup/fugle_realtime_lib/core/remote/services/IntradayService.kt
> +        @Query("apiToken") apiToken: String
@dan12411 缺少零股 parameter

<img width="740" alt="image" src="https://user-images.githubusercontent.com/17996728/215622813-dd548c4e-e54d-4360-8f50-50cfe87cb9df.png">

2023-01-30 23:57 UTC, nick45chen commented on fugle_realtime_lib/src/main/java/net/makeagoodsoup/fugle_realtime_lib/core/remote/services/IntradayService.kt
> +        @Query("apiToken") apiToken: String
btw `oddLot` 為  optional parameter (有預設值)

2023-01-31 00:00 UTC, nick45chen commented on fugle_realtime_lib/src/main/java/net/makeagoodsoup/fugle_realtime_lib/core/remote/services/IntradayService.kt
> +        @Query("apiToken") apiToken: String
nickpick:  補上文件註解說明 https://kotlinlang.org/docs/coding-conventions.html#file-annotations

2023-01-31 00:00 UTC, nick45chen commented on fugle_realtime_lib/src/main/java/net/makeagoodsoup/fugle_realtime_lib/core/repository/FugleHttpRepository.kt
> +    suspend fun getVolumes(symbolId: String, apiToken: String): Result<VolumesData> {
同 https://github.com/Make-a-good-soup/fugle-realtime-kotlin/pull/6/files#r1091283638

2023-01-31 11:38 UTC, nick45chen commented on fugle_realtime_lib/src/main/java/net/makeagoodsoup/fugle_realtime_lib/core/entities/Volume.kt
> +    val price: Double, // 成交價
已確認是文件寫錯 😂

2023-01-31 12:31 UTC, dan12411 commented on fugle_realtime_lib/src/main/java/net/makeagoodsoup/fugle_realtime_lib/core/remote/services/IntradayService.kt
> +        @Query("apiToken") apiToken: String
感謝 @nick45chen 已修正 [c29a850](https://github.com/Make-a-good-soup/fugle-realtime-kotlin/pull/6/commits/c29a850df88b61bdb2355ee91d892989b343ccae)

2023-01-31 12:31 UTC, dan12411 commented on fugle_realtime_lib/src/main/java/net/makeagoodsoup/fugle_realtime_lib/core/repository/FugleHttpRepository.kt
> +    suspend fun getVolumes(symbolId: String, apiToken: String): Result<VolumesData> {
同上

2023-01-31 12:33 UTC, dan12411 commented on fugle_realtime_lib/src/main/java/net/makeagoodsoup/fugle_realtime_lib/core/entities/Volume.kt
> +    val price: Double, // 成交價
@nick45chen  讚讚 👍🏼

2023-01-31 12:35 UTC, merged